name: meili_tool
description: Tool for managing Meilisearch Dart SDK.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  colorize: ^3.0.0
  path: ^1.8.3
  meta: ^1.11.0
  meilisearch:
    path: ../

dev_dependencies:
  lints: ">=2.1.0 <4.0.0"
