name: Publish to Pub.dev

on:
  push:
    tags:
      - v*

jobs:
  publishing:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check release validity
        run: sh .github/scripts/check-release.sh
      - name: Publish
        uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
